### ISSUE TITLE
TMPose2Scratchの認識結果ラベルが受け取れない

### ISSUE THREAD

**Issue by nobu-e758** [champierre/tmpose2scratch#2]
## 状況

Stretch3上で，TMPose2Scratch の拡張機能を使った際，

- ラベルの一覧（デフォルトだと，Normal, RightHandRaised, LeftHandRaised）は受け取れる
- 一方で，認識結果のラベル自体はやってこない（=イベントが発生しない）
- カメラ画像左上の「ポーズラベル」はずっと空白のまま変化なし

という状況が発生し，動作させることができませんでした（私以外にもう一方に試していただきましたが，同じ症状を確認しました）．一方で  classificationのTM2Scratchは問題なく動作することを確認しております．

開発ツールでコンソールを確認したとこと，以下のようなメッセージが出続けていることを確認しました．が，技術的知識，ドメイン知識が不足しており，本件と関係あるかまではわかりません（モデルのロード前に，別種のエラーも出ているようでした）

※当方の使い方間違い，勘違いであれば，申し訳ありません．

```
(387) tf-core.esm.js:17 Uncaught (in promise) TypeError: t is not a function
    at lib.min.js:326783:42337
    at lib.min.js:326783:40459
    at t.scopedRun (lib.min.js:326783:40597)
    at t.tidy (lib.min.js:326783:40361)
    at l (lib.min.js:326783:42314)
    at lib.min.js:326783:42638
    at t.scopedRun (lib.min.js:326783:40597)
    at t.runKernelFunc (lib.min.js:326783:42457)
    at t.runKernel (lib.min.js:326783:41032)
    at pad_ (lib.min.js:311926:59)
```

## 実施環境

- Windows10 PC
- Browser
    - Chrome : 97.0.4692.71
    - Edge :  97.0.1072.62

**Comment by yokobond** [comment]
TMPose2Scratchのgithub pagesでも同じエラーが出ることを確認しました。
TMPose2Scratch https://champierre.github.io/tmpose2scratch/

**Comment by yokobond** [comment]
調査中です。
現象としては、@teachablemachine/poseでtfjsを使ったときのエラーと同じようです。
最新のtensorflowを使ってしまうとだめで、v1(確実なものはv1.3.1)を使う必要があります。
どこかの変更で利用するtfjsのバージョンが変わってしまったのかもしれません。

Ref:
Error attempting to run sample snippet Teachable Machine Pose Model in TFJS 2 · Issue #125 · googlecreativelab/teachablemachine-community https://github.com/googlecreativelab/teachablemachine-community/issues/125

**Comment by yokobond** [comment]
ml5もtensorflowを使っていてnpmではバージョンを調整するのが難しかったので、#3 のようにCDN経由でteachablemachineを利用するように変更したら推定できるようになりました。

**Comment by nobu-e758** [comment]
早々の解析ならびにご対応，心から感謝いたします
https://champierre.github.io/tmpose2scratch/ 
以下では，上記環境にて正常に動作することを確認いたしました．
ありがとうございます．

**Comment by champierre** [comment]
@nobu-e758 バグのご報告ありがとうございます。stretch3 の tmpose2scratch にも修正を反映しました。
