### ISSUE TITLE
tmPose is undefined when tmpose2scratch was loaded at first. 

### ISSUE THREAD

**Issue by nagayaoh** [champierre/tmpose2scratch#4]
### Chrome起動直後かつ初回 Scratch3をロードした時点で、tmPoseがUndefinedとなり、モデルがロードされない
教育への貢献に感謝しております。
先日発売された「Scratchであそぶ機械学習（O'reilly）※1」を手にとって子供らと楽しんでおりますが、下記のIssueが見つかりましたので、ご連絡します。

#### 概要
- 初回Scratch3ロードではTMPose2Scratchがうまく動作しません。
- **【回避手段】一回「Pose分類モデルURL」を動かしてから、ページをリロードする**と、うまく動作します。

#### 再現手順
1. **一旦 Chromeを終了**させ、再度起動します
2. 上記書籍P11に指定された通り、ゲストモードでstretch3.github.ioを開く
　※ ゲストモードを使わない場合には、Chrome拡張機能 ClearCacheなどでブラウザキャッシュをクリア
3. 拡張機能読み込みからtmpose2scratchを読み込む
4. カメラ利用を許可
5. TMPose2Scratchブロックから「Pose分類モデルURL」を読み込む
6. 同ブロックから「ポーズラベル」にチェック✅を入れる
7. イベントブロックから「🚩が押された時」を読み込む
8. プレビュー画面上部の🚩をクリック
9. プレビュー画面中の「ポーズラベル」が変化しない

#### 確認したサイト
- `https://champierre.github.io/tmpose2scratch/`
　　- 上記再現手順にて確認
- `stretch3.github.io`
       - 上記再現手順にて確認
　　- [オライリーページ](https://www.oreilly.co.jp/books/9784873119960/)にある`1-1_posereaction.sb3`読み込みにて確認

#### 環境
- Mac macOs montrey 12.4
- Browser
  - Chrome : バージョン: 103.0.5060.134（Official Build） （x86_64）

#### 回避手順
上記「再現手順」を実施した後に、ページをリロードする
※ tmpose2scratchのロードを二回すればよさそうですので、もっと単純な手順があるかもしれません

#### DevToolでの確認状況
<img width="1676" alt="スクリーンショット 2022-07-31 10 00 03" src="https://user-images.githubusercontent.com/17004575/182005294-ccab80bf-767d-45a3-9219-6d73a5d4d7ee.png">

以上、よろしくお願いします

**Comment by champierre** [comment]
@nagayaoh ご指摘ありがとうございます。

https://github.com/champierre/tmpose2scratch/commit/138310992de7bb0ed39e3468f0fccce53437be8e

で修正しましたので、 https://champierre.github.io/tmpose2scratch/ でご確認いただけると助かります。

修正を確認しましたら、[stretch3](https://stretch3.github.io/) にも反映したいと思います。

**Comment by nagayaoh** [comment]
@champierre 
迅速な対応ありがとうございます。
下記のように確認させていただきました。
[stretch3](https://stretch3.github.io/) への反映、よろしくお願いします。

### ＜確認に使用した環境＞
- Mac macOs montrey 12.4
- Browser
　　- Chrome : バージョン: 103.0.5060.134（Official Build） （x86_64）
　　- ゲストモード
### ＜確認手順＞
- ゲストモードで https://champierre.github.io/tmpose2scratch/ を開く
- [オライリーページ](https://www.oreilly.co.jp/books/9784873119960/)にある1-1_posereaction.sb3を読み込む
- TMPose2Scratchブロックから「ポーズラベル」にチェック✅を入れる
- プレビュー画面上部の🚩をクリック
- およそ３０秒後、以下を確認
　　-　プレビュー画面中の「ポーズラベル」がポーズ（元々学習されているポーズ）によって変化
　　-    プレビュー画面中に🟢❌が表示される

**Comment by champierre** [comment]
@nagayaoh ありがとうございます。stretch3 の TMPose2Scratch にも修正を反映させました。
